services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/Kernel.php'

      - '../src/Contexts/**/Domain/'
      - '../src/Shared/**/Domain/'

      - '../src/Contexts/**/Application/Command/'
      - '../src/Contexts/**/Application/Query/'
      - '../src/Contexts/**/Application/DTO/'

      - '../src/Contexts/**/Infrastructure/Persistence/**/Entity/'
      - '../src/Contexts/**/Infrastructure/Http/Request/'

  App\Shared\Domain\Clock\Clock:
    alias: App\Shared\Infrastructure\Clock\SystemClock

  App\Contexts\Auth\Domain\Repository\UserRepository:
    alias: App\Contexts\Auth\Infrastructure\Persistence\Doctrine\Repository\DoctrineUserRepository

  App\Contexts\Auth\Domain\Repository\AccessTokenRepository:
    alias: App\Contexts\Auth\Infrastructure\Persistence\Doctrine\Repository\DoctrineAccessTokenRepository

  App\Contexts\Auth\Application\Port\PasswordVerifier:
    alias: App\Contexts\Auth\Infrastructure\Security\SymfonyPasswordVerifier

  App\Contexts\Auth\Domain\Service\TokenGenerator:
    alias: App\Contexts\Auth\Infrastructure\Security\RandomTokenGenerator