services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/Kernel.php'

      - '../src/Contexts/**/Domain/'
      - '../src/Shared/**/Domain/'

      - '../src/Contexts/**/Application/Command/'
      - '../src/Contexts/**/Application/Query/'
      - '../src/Contexts/**/Application/DTO/'

      - '../src/Contexts/**/Infrastructure/Persistence/**/Entity/'
      - '../src/Contexts/**/Infrastructure/Http/Request/'